[import]
    [[import.rules]]
        match="gogoproto\\.+"
        file="gogo/protobuf/gogoproto/gogo.proto"
        dependents= ["google/protobuf/descriptor.proto"]
    [[import.rules]]
        match="hdsdk.protobuf\\.+"
        file="hdsdk/protobuf/sdk.proto"
    [[import.rules]]
        match="google.protobuf.Any"
        file="google/protobuf/any.proto"
    [[import.rules]]
        match="google.protobuf.Struct"
        file="google/protobuf/struct.proto"
