[import]
    [[import.rules]]
        match="gogoproto\\.+"
        file="gogo/protobuf/gogoproto/gogo.proto"
        dependents= ["google/protobuf/descriptor.proto"]
    # DEPRECATED: 兼容老版本的github.com/hdget/hdsdk
    [[import.rules]]
        match="hdsdk.protobuf\\.+"
        file="hdsdk/protobuf/sdk.proto"
    [[import.rules]]
        match="google.protobuf.Any"
        file="google/protobuf/any.proto"
    [[import.rules]]
        match="google.protobuf.Struct"
        file="google/protobuf/struct.proto"
    [[import.rules]]
        match="hdget.protobuf\\.+"
        file="hdget/common/protobuf/sdk.proto"