package finder

type PbTypeFinder interface {
	Find(skipDirs ...string) ([]string, error) // find all <pkg>.<pbtype> in source codes
}

// New create a new PbTypeFinder, now it only supports find pb types which generated by gogo-protoc from golang source codes
func New(sourceDir, pbPkgPath string) PbTypeFinder {
	return newGolangAstFinder(sourceDir, pbPkgPath)
}
